.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. bgold_qt test_bgold_qt
clean: FORCE
	$(MAKE) -C .. bgold_qt_clean test_bgold_qt_clean
check: FORCE
	$(MAKE) -C .. test_bgold_qt_check
bgold-qt bgold-qt.exe: FORCE
	 $(MAKE) -C .. bgold_qt
